name: Build and Deploy Code

on: [push, pull_request]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        usages: actions/checkout@v2
      - name: say hi to zed
        run: echo "hi zed"
